### ISSUE TITLE
Failed to activate the emmet-jsx-css-modules package

### ISSUE THREAD

**Issue by shaohailong** [ambethia/emmet-jsx-css-modules#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.0-beta2
**System**: Mac OS X 10.11.6
**Thrown From**: [emmet-jsx-css-modules](https://github.com/ambethia/emmet-jsx-css-modules) package, v0.2.0
### Stack Trace

Failed to activate the emmet-jsx-css-modules package

```
At path.resolve is not a function

TypeError: path.resolve is not a function
    at Object.activate (/Users/lucas/.atom/packages/emmet-jsx-css-modules/lib/emmet-jsx-css-modules.js:7:28)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```
### Commands

```
  2x -2:55.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:54.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:54.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:54.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:54.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:54.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:54.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:54.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:37.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:37.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:37.7.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -1:37 core:backspace (atom-text-editor.editor.is-focused)
     -1:34.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:01.1.0 settings-view:open (atom-text-editor.editor.is-focused)
 10x -0:58.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:54.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.3 (active)
atom-beautify, v0.29.9 (active)
emmet, v2.4.3 (active)
emmet-jsx-css-modules, v0.2.0 (inactive)
markdown-image-helper, v1.0.4 (active)
markdown-themeable-pdf, v1.1.1 (active)
pdf-view, v0.50.0 (active)
pigments, v0.30.0 (active)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.1 (active)
tidy-markdown, v3.0.1 (active)
yeti-syntax, v0.1.2 (inactive)
yeti-ui, v0.1.6 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ambethia** [comment]
Have you been able to resolve this?

**Comment by springxiege** [comment]
I've had this problem too.

**Comment by Edge00** [comment]
![1](https://cloud.githubusercontent.com/assets/23715779/24942542/417c9d86-1f84-11e7-968b-15ede9332470.png)

**Comment by ambethia** [comment]
I haven't been able to reproduce this. I would need more info about what's causing it for you.

**Comment by aFcFzF** [comment]
how to resolve it ? I  need this plug.

**Comment by ambethia** [comment]
I'm still going to need more info to reproduce this before a solution can be found.

**Comment by bakthaa** [comment]
Hi, I tried to install manually due to package download problem from setting option.

I could not find "src" folder under C:/dev/bin/Atom x64/resources/app/ folder. (Note: I installed ATOM through zip file.)

### Stack Trace

Failed to activate the emmet-jsx-css-modules package

```
At Path must be a string. Received null

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at /packages/emmet-jsx-css-modules/lib/emmet-jsx-css-modules.js:25:28
    at Object.activate (/packages/emmet-jsx-css-modules/lib/emmet-jsx-css-modules.js:68:79)
    at Package.module.exports.Package.activateNow (C:/dev/bin/Atom x64/resources/app/src/package.js:255:25)
    at C:/dev/bin/Atom x64/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (C:/dev/bin/Atom x64/resources/app/src/package.js:99:21)
    at C:/dev/bin/Atom x64/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (C:/dev/bin/Atom x64/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (C:/dev/bin/Atom x64/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (C:/dev/bin/Atom x64/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (C:/dev/bin/Atom x64/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (C:/dev/bin/Atom x64/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (C:/dev/bin/Atom x64/resources/app/src/package-manager.js:647:50)
    at C:/dev/bin/Atom x64/resources/app/src/atom-environment.js:865:36
```

**Comment by jbwyatt4** [comment]
I was able to reproduce this issue after months of not having issue with this package.

For me it was caused by a init.js file being created in .atom on Linux. The file can be completely empty and it will trigger it.
